import { FC, useState, useEffect, useRef } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { toast } from '@/hooks/use-toast';
import { 
  Upload, Trash2, RefreshCw, FileCode, Copy, ExternalLink, Shield
} from 'lucide-react';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Badge } from '@/components/ui/badge';

interface UploadedScript {
  id: string;
  name: string;
  display_name: string;
  description: string | null;
  content: string;
  script_type: string;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

const WHITELIST_WRAPPER = (apiUrl: string, userScript: string) => `-- ========================================
-- WHITELIST PROTECTED SCRIPT
-- Auto-generated by Arexans System
-- ========================================

local HttpService = game:GetService("HttpService")
local Players = game:GetService("Players")

local WHITELIST_API = "${apiUrl}/get-whitelist?format=json"
local FAKE_SCRIPT_API = "${apiUrl}/get-fake-script"
local CHECK_INTERVAL = 60

local whitelistCache = {}
local lastFetch = 0
local CACHE_DURATION = 30

local function fetchWhitelist()
    local success, result = pcall(function()
        local response = game:HttpGet(WHITELIST_API)
        local data = HttpService:JSONDecode(response)
        if data.success then return data.usernames end
        return {}
    end)
    if success then
        whitelistCache = result or {}
        lastFetch = tick()
        return true
    end
    return false
end

local function isWhitelisted(username)
    if tick() - lastFetch > CACHE_DURATION then fetchWhitelist() end
    for _, name in ipairs(whitelistCache) do
        if string.lower(name) == string.lower(username) then return true end
    end
    return false
end

local function getCurrentUsername()
    local player = Players.LocalPlayer
    if player then return player.Name end
    return nil
end

local function loadFakeScript()
    local success, fakeCode = pcall(function()
        return game:HttpGet(FAKE_SCRIPT_API)
    end)
    if success and fakeCode then
        pcall(function() loadstring(fakeCode)() end)
    else
        print("[Arexans] Loading script...")
        for i = 1, 5 do
            print("Initializing module " .. i .. "/5...")
            wait(0.5)
        end
        print("Error: Connection timeout. Please try again later.")
    end
end

local username = getCurrentUsername()
if not username then
    warn("[Whitelist] Could not get player username")
    return
end

fetchWhitelist()

if not isWhitelisted(username) then
    loadFakeScript()
    return
end

print("[Arexans] Whitelist verified! Loading script...")

-- ========================================
-- PROTECTED SCRIPT
-- ========================================

${userScript}

-- Periodic check
spawn(function()
    while wait(CHECK_INTERVAL) do
        if not isWhitelisted(getCurrentUsername()) then
            warn("[Whitelist] User no longer whitelisted!")
        end
    end
end)
`;

const LuaUploadManager: FC = () => {
  const [scripts, setScripts] = useState<UploadedScript[]>([]);
  const [loading, setLoading] = useState(false);
  const [uploading, setUploading] = useState(false);
  const fileInputRef = useRef<HTMLInputElement | null>(null);

  const SUPABASE_API_BASE = `${import.meta.env.VITE_SUPABASE_URL}/functions/v1`;

  const fetchScripts = async () => {
    setLoading(true);
    try {
      const { data, error } = await supabase
        .from('lua_scripts')
        .select('*')
        .eq('script_type', 'uploaded')
        .order('created_at', { ascending: false });

      if (error) throw error;
      setScripts(data || []);
    } catch (error) {
      console.error('Failed to fetch uploaded scripts:', error);
      toast({ title: 'Error', description: 'Gagal mengambil data scripts', variant: 'destructive' });
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => { fetchScripts(); }, []);

  const handleUpload = async (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (!file) return;

    const ext = file.name.toLowerCase().substring(file.name.lastIndexOf('.'));
    if (!['.lua', '.txt'].includes(ext)) {
      toast({ title: 'Error', description: 'Hanya file .lua atau .txt', variant: 'destructive' });
      return;
    }

    setUploading(true);
    try {
      const rawContent = await file.text();
      const scriptName = file.name.replace(/\.(lua|txt)$/i, '').replace(/[^a-zA-Z0-9_-]/g, '_').toLowerCase();
      
      const wrappedContent = WHITELIST_WRAPPER(SUPABASE_API_BASE, rawContent);

      const { data: existing } = await supabase
        .from('lua_scripts')
        .select('id')
        .eq('name', `uploaded_${scriptName}`)
        .maybeSingle();

      if (existing) {
        const { error } = await supabase
          .from('lua_scripts')
          .update({
            content: wrappedContent,
            updated_at: new Date().toISOString(),
          })
          .eq('id', existing.id);
        if (error) throw error;
        toast({ title: 'Berhasil', description: `Script "${file.name}" berhasil diupdate dengan whitelist protection` });
      } else {
        const { error } = await supabase
          .from('lua_scripts')
          .insert({
            name: `uploaded_${scriptName}`,
            display_name: file.name,
            description: `Uploaded script with whitelist protection`,
            content: wrappedContent,
            script_type: 'uploaded',
            is_active: true,
          });
        if (error) throw error;
        toast({ title: 'Berhasil', description: `Script "${file.name}" berhasil diupload dengan whitelist protection` });
      }

      fetchScripts();
    } catch (error) {
      console.error('Upload failed:', error);
      toast({ title: 'Error', description: 'Gagal mengupload script', variant: 'destructive' });
    } finally {
      setUploading(false);
      event.target.value = '';
    }
  };

  const deleteScript = async (id: string, name: string) => {
    try {
      const { error } = await supabase.from('lua_scripts').delete().eq('id', id);
      if (error) throw error;
      toast({ title: 'Berhasil', description: `Script "${name}" berhasil dihapus` });
      fetchScripts();
    } catch (error) {
      console.error('Delete failed:', error);
      toast({ title: 'Error', description: 'Gagal menghapus script', variant: 'destructive' });
    }
  };

  const getScriptUrl = (scriptName: string) => `${SUPABASE_API_BASE}/get-script?name=${scriptName}&token=AXS-SECURE-2026-RBLX`;

  const copyUrl = (scriptName: string) => {
    navigator.clipboard.writeText(getScriptUrl(scriptName));
    toast({ title: 'Copied!', description: 'URL berhasil disalin' });
  };

  const getLoaderUrl = (scriptName: string) => `${SUPABASE_API_BASE}/get-loader?name=${scriptName}`;

  const generateObfuscatedBootstrap = (url: string): string => {
    const bytes = Array.from(new TextEncoder().encode(url));
    const bytesStr = bytes.join(",");
    const chars = "abcdefghijklmnopqrstuvwxyz";
    const rv = () => { let r = "_"; for (let i = 0; i < 6; i++) r += chars[Math.floor(Math.random() * chars.length)]; return r; };
    const v1 = rv(), v2 = rv(), v3 = rv(), v4 = rv(), v5 = rv();
    return `do local ${v1}={${bytesStr}} local ${v2}="" for _,${v3} in ipairs(${v1}) do ${v2}=${v2}..string.char(${v3}) end local ${v4},${v5}=pcall(function() return game:HttpGet(${v2}) end) if ${v4} and ${v5} then pcall(function() (function(...) return select(1,...)() end)(load or loadstring)(${v5}) end) end end`;
  };

  const copyLoadstring = (scriptName: string) => {
    const code = generateObfuscatedBootstrap(getLoaderUrl(scriptName));
    navigator.clipboard.writeText(code);
    toast({ title: 'Copied!', description: 'Obfuscated bootstrap code berhasil disalin' });
  };

  return (
    <div className="space-y-4 sm:space-y-6">
      <div className="flex items-start justify-between gap-2">
        <div className="min-w-0 flex-1">
          <h2 className="text-lg sm:text-xl font-display font-semibold flex items-center gap-2">
            <Upload className="w-4 h-4 sm:w-5 sm:h-5 text-primary flex-shrink-0" />
            <span className="truncate">Upload Lua Scripts</span>
          </h2>
          <p className="text-xs sm:text-sm text-muted-foreground">
            Upload file .lua — otomatis di-wrap dengan whitelist protection
          </p>
        </div>
        <Button variant="outline" size="sm" onClick={fetchScripts} disabled={loading} className="flex-shrink-0">
          <RefreshCw className={`w-4 h-4 ${loading ? 'animate-spin' : ''}`} />
        </Button>
      </div>

      {/* Upload Area */}
      <Card className="glass-card">
        <CardContent className="p-4 sm:p-6">
          <input
            type="file"
            accept=".lua,.txt"
            ref={fileInputRef}
            onChange={handleUpload}
            className="hidden"
          />
          <div
            onClick={() => fileInputRef.current?.click()}
            className="border-2 border-dashed border-primary/30 rounded-xl p-6 sm:p-8 text-center cursor-pointer hover:border-primary/60 hover:bg-primary/5 transition-all"
          >
            <Upload className="w-8 h-8 sm:w-10 sm:h-10 mx-auto mb-3 text-primary/50" />
            <p className="text-sm font-medium mb-1">
              {uploading ? 'Uploading...' : 'Klik untuk upload file Lua'}
            </p>
            <p className="text-xs text-muted-foreground">
              File .lua atau .txt — otomatis di-wrap dengan whitelist + fake script protection
            </p>
          </div>
          <div className="mt-3 p-2 rounded bg-primary/10 border border-primary/20">
            <div className="flex items-center gap-2 text-xs text-primary">
              <Shield className="w-3 h-3 flex-shrink-0" />
              <span>Script yang diupload akan otomatis terproteksi whitelist. User yang tidak terdaftar akan mendapat fake source code.</span>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Uploaded Scripts List */}
      <Card className="glass-card">
        <CardHeader className="pb-3 px-3 sm:px-6">
          <CardTitle className="text-sm sm:text-base flex items-center gap-2">
            <FileCode className="w-4 h-4 text-primary" />
            Script Ter-upload ({scripts.length})
          </CardTitle>
          <CardDescription className="text-xs">
            Semua script sudah terproteksi whitelist
          </CardDescription>
        </CardHeader>
        <CardContent className="px-3 sm:px-6">
          {scripts.length === 0 ? (
            <div className="text-center py-8 text-muted-foreground">
              <FileCode className="w-12 h-12 mx-auto mb-2 opacity-30" />
              <p className="text-sm">Belum ada script yang diupload</p>
            </div>
          ) : (
            <ScrollArea className="max-h-[400px]">
              <div className="space-y-3">
                {scripts.map((script) => (
                  <div key={script.id} className="p-3 rounded-lg bg-muted/30 hover:bg-muted/50 transition-colors space-y-2">
                    <div className="flex items-center justify-between gap-2">
                      <div className="min-w-0 flex-1">
                        <div className="flex items-center gap-2">
                          <p className="font-medium text-sm truncate">{script.display_name}</p>
                          <Badge variant="outline" className="text-[10px] px-1.5 py-0 flex-shrink-0">
                            <Shield className="w-2.5 h-2.5 mr-0.5" />
                            Protected
                          </Badge>
                        </div>
                        <p className="text-[10px] text-muted-foreground">
                          {new Date(script.updated_at).toLocaleString('id-ID')}
                        </p>
                      </div>
                      <Button
                        variant="ghost"
                        size="sm"
                        onClick={() => deleteScript(script.id, script.display_name)}
                        className="text-destructive hover:text-destructive flex-shrink-0"
                      >
                        <Trash2 className="w-4 h-4" />
                      </Button>
                    </div>
                    
                    <div className="space-y-1.5">
                      <div className="flex gap-1.5">
                        <Input
                          readOnly
                          value={getScriptUrl(script.name)}
                          className="font-mono text-[10px] h-7 bg-black/30"
                        />
                        <Button variant="outline" size="sm" className="h-7 px-2" onClick={() => copyUrl(script.name)}>
                          <Copy className="w-3 h-3" />
                        </Button>
                        <Button variant="outline" size="sm" className="h-7 px-2" onClick={() => window.open(getScriptUrl(script.name), '_blank')}>
                          <ExternalLink className="w-3 h-3" />
                        </Button>
                      </div>
                      <Button variant="outline" size="sm" className="w-full text-xs h-7" onClick={() => copyLoadstring(script.name)}>
                        <Copy className="w-3 h-3 mr-1" />
                        Copy Loadstring
                      </Button>
                    </div>
                  </div>
                ))}
              </div>
            </ScrollArea>
          )}
        </CardContent>
      </Card>

      {/* Fake Script API Info */}
      <Card className="glass-card">
        <CardHeader className="pb-3 px-3 sm:px-6">
          <CardTitle className="text-sm sm:text-base flex items-center gap-2">
            <Shield className="w-4 h-4 text-yellow-500" />
            Fake Script API
          </CardTitle>
          <CardDescription className="text-xs">
            Endpoint yang mengembalikan source code palsu untuk user non-whitelist
          </CardDescription>
        </CardHeader>
        <CardContent className="px-3 sm:px-6 space-y-2">
          <div className="flex gap-1.5">
            <Input
              readOnly
              value={`${SUPABASE_API_BASE}/get-fake-script`}
              className="font-mono text-xs bg-black/30"
            />
            <Button variant="outline" size="sm" onClick={() => {
              navigator.clipboard.writeText(`${SUPABASE_API_BASE}/get-fake-script`);
              toast({ title: 'Copied!' });
            }}>
              <Copy className="w-3 h-3" />
            </Button>
          </div>
          <p className="text-xs text-muted-foreground">
            User yang tidak ada di whitelist akan mendapat script palsu yang menampilkan pesan error fake, sementara user yang terdaftar mendapat script asli.
          </p>
        </CardContent>
      </Card>
    </div>
  );
};

export default LuaUploadManager;
