import { FC, useState, useEffect, useRef } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { toast } from '@/hooks/use-toast';
import {
  Upload, Trash2, RefreshCw, FileCode, Copy, ExternalLink, Shield,
  History as HistoryIcon, Undo2, Redo2, RotateCcw,
} from 'lucide-react';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Badge } from '@/components/ui/badge';
import {
  Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription,
} from '@/components/ui/dialog';

interface UploadedScript {
  id: string;
  name: string;
  display_name: string;
  description: string | null;
  content: string;
  script_type: string;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

interface ScriptVersion {
  id: string;
  script_id: string;
  version_number: number;
  content: string;
  display_name: string | null;
  created_at: string;
}

const textToBase64 = (text: string) => {
  const bytes = new TextEncoder().encode(text);
  let binary = '';
  for (let i = 0; i < bytes.length; i += 0x8000) {
    binary += String.fromCharCode(...bytes.slice(i, i + 0x8000));
  }
  return btoa(binary);
};

const base64ToText = (value: string) => {
  const binary = atob(value);
  const bytes = Uint8Array.from(binary, (char) => char.charCodeAt(0));
  return new TextDecoder().decode(bytes);
};

const luaChunkedString = (text: string) => {
  const bytes = new TextEncoder().encode(text);
  const lines = ['(function() local t={} local n=0'];
  for (let i = 0; i < bytes.length; i += 180) {
    lines.push(`n=n+1 t[n]=string.char(${Array.from(bytes.slice(i, i + 180)).join(',')})`);
  }
  lines.push('return table.concat(t) end)()');
  return lines.join(' ');
};

/**
 * Protection wrapper: integrasi key system + whitelist + session cache.
 * Saat dieksekusi:
 *   1) Cek ArexansTools/ArexansTools_Session.json → kalau ada key valid, jalan langsung.
 *   2) Cek whitelist username (manual + license robloxUsers) di server.
 *   3) Kalau tidak whitelist, prompt input AXS key → simpan ke session file.
 *   4) Kalau key invalid → fake script.
 */
const PROTECTION_WRAPPER = (apiBase: string, userScript: string) => `--[[
============================================================
 ArexansTools — Auto-Protected Script
 Integrasi: Key System + Whitelist + Session Cache
 Generated by Lua Upload Manager
============================================================
]]
-- AREXANS_RAW_B64:${textToBase64(userScript)}
do
local HttpService        = game:GetService("HttpService")
local Players            = game:GetService("Players")
local CoreGui            = game:GetService("CoreGui")
local TweenService       = game:GetService("TweenService")
local UserInputService   = game:GetService("UserInputService")

local API_BASE         = "${apiBase}"
local WHITELIST_API    = API_BASE .. "/get-whitelist?format=json"
local FAKE_SCRIPT_API  = API_BASE .. "/get-fake-script"
local VALIDATE_KEY_API = API_BASE .. "/validate-key"

local SESSION_FOLDER   = "ArexansTools"
local SESSION_FILE     = SESSION_FOLDER .. "/ArexansTools_Session.json"

local LocalPlayer = Players.LocalPlayer or Players.PlayerAdded:Wait()
local username    = LocalPlayer.Name

local function getHwid()
    local ok, id = pcall(function()
        return game:GetService("RbxAnalyticsService"):GetClientId()
    end)
    return ok and id or (tostring(LocalPlayer.UserId) .. "_fallback")
end
local HWID = getHwid()

-- ===== Filesystem helpers =====
local function safeRead()
    if not (isfile and readfile) then return nil end
    if not isfile(SESSION_FILE) then return nil end
    local ok, raw = pcall(readfile, SESSION_FILE)
    if not ok or not raw or raw == "" then return nil end
    local ok2, data = pcall(function() return HttpService:JSONDecode(raw) end)
    if ok2 and type(data) == "table" then return data end
    return nil
end
local function safeWrite(tbl)
    if not (writefile and makefolder) then return end
    pcall(function()
        if isfolder and not isfolder(SESSION_FOLDER) then makefolder(SESSION_FOLDER) end
        writefile(SESSION_FILE, HttpService:JSONEncode(tbl))
    end)
end
local function safeDelete()
    if delfile and isfile and isfile(SESSION_FILE) then
        pcall(delfile, SESSION_FILE)
    end
end

-- ===== HTTP =====
local function httpRequest(opts)
    local req = (syn and syn.request) or (http and http.request) or (fluxus and fluxus.request) or request or http_request
    if not req then
        local ok, body = pcall(function() return game:HttpGet(opts.Url) end)
        return ok and { StatusCode = 200, Body = body } or nil
    end
    local ok, res = pcall(req, opts)
    return ok and res or nil
end

local function validateKey(key)
    local res = httpRequest({
        Url = VALIDATE_KEY_API,
        Method = "POST",
        Headers = { ["Content-Type"] = "application/json" },
        Body = HttpService:JSONEncode({ key = key, hwid = HWID, robloxUsername = username }),
    })
    if not res or not res.Body then return false, "Koneksi gagal" end
    local ok, parsed = pcall(function() return HttpService:JSONDecode(res.Body) end)
    if ok and parsed and parsed.success and parsed.valid then
        return true, parsed
    end
    local msg = (ok and parsed and (parsed.error or parsed.message)) or "Key tidak valid"
    return false, msg
end

-- ===== Step 1: cached session key =====
local function tryCachedKey()
    local data = safeRead()
    if not data or not data.key or data.key == "" then return false end
    local ok, parsed = validateKey(data.key)
    if ok then
        print("[ArexansTools] Session key valid (role: " .. tostring(parsed.role) .. ")")
        return true
    end
    safeDelete()
    return false
end

-- ===== Step 2: whitelist =====
local function checkWhitelist()
    local res = httpRequest({ Url = WHITELIST_API, Method = "GET" })
    if not res or not res.Body then return false end
    local ok, data = pcall(function() return HttpService:JSONDecode(res.Body) end)
    if not (ok and data and data.success and data.usernames) then return false end
    local lname = string.lower(username)
    for _, u in ipairs(data.usernames) do
        if string.lower(u) == lname then return true end
    end
    return false
end

-- ===== Step 3: Cyberpunk Key Prompt UI =====
local function promptKeyUI()
    -- Bersihkan UI lama
    local old = CoreGui:FindFirstChild("ArexansKeyPrompt")
    if old then old:Destroy() end

    local gui = Instance.new("ScreenGui")
    gui.Name = "ArexansKeyPrompt"
    gui.ResetOnSpawn = false
    gui.ZIndexBehavior = Enum.ZIndexBehavior.Sibling
    gui.IgnoreGuiInset = true
    pcall(function() gui.Parent = (gethui and gethui()) or CoreGui end)
    if not gui.Parent then gui.Parent = LocalPlayer:WaitForChild("PlayerGui") end

    -- Backdrop
    local backdrop = Instance.new("Frame", gui)
    backdrop.Size = UDim2.fromScale(1,1)
    backdrop.BackgroundColor3 = Color3.fromRGB(5, 5, 15)
    backdrop.BackgroundTransparency = 0.35
    backdrop.BorderSizePixel = 0

    -- Main panel
    local panel = Instance.new("Frame", gui)
    panel.Size = UDim2.fromOffset(360, 280)
    panel.Position = UDim2.new(0.5, -180, 0.5, -140)
    panel.BackgroundColor3 = Color3.fromRGB(12, 14, 28)
    panel.BorderSizePixel = 0
    Instance.new("UICorner", panel).CornerRadius = UDim.new(0, 14)
    local stroke = Instance.new("UIStroke", panel)
    stroke.Color = Color3.fromRGB(0, 220, 255)
    stroke.Thickness = 1.5
    stroke.Transparency = 0.2

    -- Header glow bar
    local header = Instance.new("Frame", panel)
    header.Size = UDim2.new(1, 0, 0, 50)
    header.BackgroundColor3 = Color3.fromRGB(0, 220, 255)
    header.BackgroundTransparency = 0.85
    header.BorderSizePixel = 0
    Instance.new("UICorner", header).CornerRadius = UDim.new(0, 14)

    local title = Instance.new("TextLabel", header)
    title.Size = UDim2.new(1, -20, 1, 0)
    title.Position = UDim2.fromOffset(15, 0)
    title.BackgroundTransparency = 1
    title.Font = Enum.Font.GothamBold
    title.Text = "🔐  AREXANSTOOLS  ·  KEY SYSTEM"
    title.TextColor3 = Color3.fromRGB(0, 230, 255)
    title.TextSize = 14
    title.TextXAlignment = Enum.TextXAlignment.Left

    -- Subtitle
    local sub = Instance.new("TextLabel", panel)
    sub.Size = UDim2.new(1, -30, 0, 40)
    sub.Position = UDim2.fromOffset(15, 60)
    sub.BackgroundTransparency = 1
    sub.Font = Enum.Font.Gotham
    sub.Text = "Hi " .. username .. "! Masukkan AXS key kamu untuk mengakses script. Key akan disimpan otomatis."
    sub.TextColor3 = Color3.fromRGB(180, 200, 220)
    sub.TextSize = 12
    sub.TextWrapped = true
    sub.TextXAlignment = Enum.TextXAlignment.Left
    sub.TextYAlignment = Enum.TextYAlignment.Top

    -- Input box
    local input = Instance.new("TextBox", panel)
    input.Size = UDim2.new(1, -30, 0, 42)
    input.Position = UDim2.fromOffset(15, 115)
    input.BackgroundColor3 = Color3.fromRGB(20, 24, 40)
    input.BorderSizePixel = 0
    input.PlaceholderText = "AXS-XXXXXXXX"
    input.Text = ""
    input.Font = Enum.Font.Code
    input.TextColor3 = Color3.fromRGB(255, 255, 255)
    input.PlaceholderColor3 = Color3.fromRGB(100, 110, 130)
    input.TextSize = 14
    input.ClearTextOnFocus = false
    Instance.new("UICorner", input).CornerRadius = UDim.new(0, 8)
    local inputStroke = Instance.new("UIStroke", input)
    inputStroke.Color = Color3.fromRGB(140, 80, 255)
    inputStroke.Transparency = 0.5

    -- Status label
    local status = Instance.new("TextLabel", panel)
    status.Size = UDim2.new(1, -30, 0, 18)
    status.Position = UDim2.fromOffset(15, 165)
    status.BackgroundTransparency = 1
    status.Font = Enum.Font.Gotham
    status.Text = ""
    status.TextColor3 = Color3.fromRGB(255, 90, 110)
    status.TextSize = 11
    status.TextXAlignment = Enum.TextXAlignment.Left

    -- Submit button
    local btn = Instance.new("TextButton", panel)
    btn.Size = UDim2.new(1, -30, 0, 40)
    btn.Position = UDim2.new(0, 15, 1, -90)
    btn.BackgroundColor3 = Color3.fromRGB(0, 220, 255)
    btn.BorderSizePixel = 0
    btn.AutoButtonColor = false
    btn.Font = Enum.Font.GothamBold
    btn.Text = "VERIFIKASI & LANJUTKAN"
    btn.TextColor3 = Color3.fromRGB(10, 12, 25)
    btn.TextSize = 13
    Instance.new("UICorner", btn).CornerRadius = UDim.new(0, 8)

    -- Cancel button
    local cancel = Instance.new("TextButton", panel)
    cancel.Size = UDim2.new(1, -30, 0, 30)
    cancel.Position = UDim2.new(0, 15, 1, -42)
    cancel.BackgroundTransparency = 1
    cancel.Font = Enum.Font.Gotham
    cancel.Text = "Batal"
    cancel.TextColor3 = Color3.fromRGB(140, 150, 170)
    cancel.TextSize = 12

    -- State
    local done = false
    local result = nil

    local function setStatus(text, isError)
        status.Text = text or ""
        status.TextColor3 = isError and Color3.fromRGB(255,90,110) or Color3.fromRGB(0,230,180)
    end

    local function submit()
        local key = input.Text:gsub("%s+", "")
        if key == "" then setStatus("Key tidak boleh kosong", true); return end
        btn.Text = "MEMVERIFIKASI..."
        btn.Active = false
        setStatus("Menghubungi server...", false)
        task.spawn(function()
            local ok, parsed = validateKey(key)
            if ok then
                safeWrite({ key = key, savedAt = os.time(), role = parsed.role })
                setStatus("✓ Berhasil! Memuat script...", false)
                task.wait(0.4)
                result = true
                done = true
                gui:Destroy()
            else
                btn.Text = "VERIFIKASI & LANJUTKAN"
                btn.Active = true
                setStatus("✗ " .. tostring(parsed), true)
            end
        end)
    end

    btn.MouseButton1Click:Connect(submit)
    input.FocusLost:Connect(function(enter) if enter then submit() end end)
    cancel.MouseButton1Click:Connect(function()
        result = false
        done = true
        gui:Destroy()
    end)

    -- Draggable
    do
        local dragging, dragStart, startPos = false, nil, nil
        header.InputBegan:Connect(function(i)
            if i.UserInputType == Enum.UserInputType.MouseButton1 or i.UserInputType == Enum.UserInputType.Touch then
                dragging = true; dragStart = i.Position; startPos = panel.Position
            end
        end)
        UserInputService.InputChanged:Connect(function(i)
            if dragging and (i.UserInputType == Enum.UserInputType.MouseMovement or i.UserInputType == Enum.UserInputType.Touch) then
                local d = i.Position - dragStart
                panel.Position = UDim2.new(startPos.X.Scale, startPos.X.Offset + d.X, startPos.Y.Scale, startPos.Y.Offset + d.Y)
            end
        end)
        UserInputService.InputEnded:Connect(function(i)
            if i.UserInputType == Enum.UserInputType.MouseButton1 or i.UserInputType == Enum.UserInputType.Touch then
                dragging = false
            end
        end)
    end

    -- Wait until user submits / cancels
    while not done do task.wait(0.1) end
    return result == true
end

-- ===== Fake fallback =====
local function runFake()
    local res = httpRequest({ Url = FAKE_SCRIPT_API, Method = "GET" })
    if res and res.Body then
        pcall(function() loadstring(res.Body)() end)
    else
        warn("[ArexansTools] Akses ditolak.")
    end
end

-- ===== Main gate =====
local authorized = false

if tryCachedKey() then
    authorized = true
elseif checkWhitelist() then
    authorized = true
    print("[ArexansTools] Whitelist verified for " .. username)
elseif promptKeyUI() then
    authorized = true
end

if not authorized then
    runFake()
    return
end

print("[ArexansTools] Access granted. Loading script...")
end

-- ============================================================
-- USER SCRIPT (PROTECTED)
-- ============================================================
local __arexans_source = ${luaChunkedString(userScript)}
local __arexans_load = loadstring or load
if not __arexans_load then error("[ArexansTools] Executor tidak support loadstring/load") end
local __arexans_fn, __arexans_err = __arexans_load(__arexans_source)
if not __arexans_fn then error(__arexans_err) end
return __arexans_fn()
`;

const LuaUploadManager: FC = () => {
  const [scripts, setScripts] = useState<UploadedScript[]>([]);
  const [loading, setLoading] = useState(false);
  const [uploading, setUploading] = useState(false);
  const [rewrapping, setRewrapping] = useState(false);
  const [versions, setVersions] = useState<ScriptVersion[]>([]);
  const [historyScript, setHistoryScript] = useState<UploadedScript | null>(null);
  const [previewVersion, setPreviewVersion] = useState<ScriptVersion | null>(null);
  const fileInputRef = useRef<HTMLInputElement | null>(null);

  const SUPABASE_API_BASE = `${import.meta.env.VITE_SUPABASE_URL}/functions/v1`;

  const fetchScripts = async () => {
    setLoading(true);
    try {
      const { data, error } = await supabase
        .from('lua_scripts')
        .select('*')
        .eq('script_type', 'uploaded')
        .order('created_at', { ascending: false });
      if (error) throw error;
      setScripts(data || []);
    } catch (e) {
      toast({ title: 'Error', description: 'Gagal mengambil scripts', variant: 'destructive' });
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => { fetchScripts(); }, []);

  const wrap = (raw: string) => PROTECTION_WRAPPER(SUPABASE_API_BASE, raw);

  const unwrap = (wrapped: string): string => {
    const rawB64 = wrapped.match(/-- AREXANS_RAW_B64:([^\r\n]+)/)?.[1];
    if (rawB64) {
      try { return base64ToText(rawB64); } catch { /* fallback to marker parsing */ }
    }
    const marker = '-- USER SCRIPT (PROTECTED)';
    const idx = wrapped.indexOf(marker);
    if (idx === -1) return wrapped;
    // Skip marker line plus optional divider line so old scripts can be re-wrapped cleanly.
    const afterMarker = wrapped.substring(idx + marker.length);
    return afterMarker.replace(/^\r?\n-- ={10,}\r?\n/, '').replace(/^\r?\n/, '').replace(/\n$/, '');
  };

  const handleUpload = async (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (!file) return;
    const ext = file.name.toLowerCase().substring(file.name.lastIndexOf('.'));
    if (!['.lua', '.txt'].includes(ext)) {
      toast({ title: 'Error', description: 'Hanya .lua atau .txt', variant: 'destructive' });
      return;
    }
    setUploading(true);
    try {
      const raw = await file.text();
      const scriptName = file.name.replace(/\.(lua|txt)$/i, '').replace(/[^a-zA-Z0-9_-]/g, '_').toLowerCase();
      const wrapped = wrap(raw);
      const dbName = `uploaded_${scriptName}`;

      const { data: existing } = await supabase.from('lua_scripts').select('id').eq('name', dbName).maybeSingle();
      if (existing) {
        const { error } = await supabase.from('lua_scripts')
          .update({ content: wrapped, updated_at: new Date().toISOString() }).eq('id', existing.id);
        if (error) throw error;
        toast({ title: 'Berhasil', description: `"${file.name}" diupdate (key + whitelist auto-terintegrasi)` });
      } else {
        const { error } = await supabase.from('lua_scripts').insert({
          name: dbName, display_name: file.name,
          description: 'Auto-integrated: key system + whitelist',
          content: wrapped, script_type: 'uploaded', is_active: true,
        });
        if (error) throw error;
        toast({ title: 'Berhasil', description: `"${file.name}" diupload (key + whitelist auto-terintegrasi)` });
      }
      fetchScripts();
    } catch (e) {
      toast({ title: 'Error', description: 'Gagal upload', variant: 'destructive' });
    } finally {
      setUploading(false);
      event.target.value = '';
    }
  };

  const reWrapAll = async () => {
    if (!confirm('Re-wrap semua script dengan wrapper terbaru (key system + whitelist)?')) return;
    setRewrapping(true);
    try {
      for (const s of scripts) {
        const raw = unwrap(s.content);
        const newWrapped = wrap(raw);
        await supabase.from('lua_scripts').update({
          content: newWrapped, updated_at: new Date().toISOString(),
        }).eq('id', s.id);
      }
      toast({ title: 'Berhasil', description: `${scripts.length} script di-rewrap` });
      fetchScripts();
    } catch (e) {
      toast({ title: 'Error', description: 'Gagal re-wrap', variant: 'destructive' });
    } finally {
      setRewrapping(false);
    }
  };

  const deleteScript = async (id: string, name: string) => {
    try {
      const { error } = await supabase.from('lua_scripts').delete().eq('id', id);
      if (error) throw error;
      toast({ title: 'Berhasil', description: `"${name}" dihapus` });
      fetchScripts();
    } catch {
      toast({ title: 'Error', description: 'Gagal menghapus', variant: 'destructive' });
    }
  };

  const openHistory = async (script: UploadedScript) => {
    setHistoryScript(script);
    setPreviewVersion(null);
    const { data, error } = await supabase
      .from('lua_script_versions')
      .select('*')
      .eq('script_id', script.id)
      .order('version_number', { ascending: false });
    if (error) {
      toast({ title: 'Error', description: 'Gagal load history', variant: 'destructive' });
      return;
    }
    setVersions(data || []);
  };

  const restoreVersion = async (version: ScriptVersion) => {
    if (!historyScript) return;
    if (!confirm(`Restore versi #${version.version_number}? Versi saat ini akan disimpan ke history.`)) return;
    const { error } = await supabase.from('lua_scripts').update({
      content: version.content, updated_at: new Date().toISOString(),
    }).eq('id', historyScript.id);
    if (error) {
      toast({ title: 'Error', description: 'Gagal restore', variant: 'destructive' });
      return;
    }
    toast({ title: 'Berhasil', description: `Restored ke v${version.version_number}` });
    setHistoryScript(null);
    fetchScripts();
  };

  const undoToPrevious = async (script: UploadedScript) => {
    const { data } = await supabase
      .from('lua_script_versions')
      .select('*')
      .eq('script_id', script.id)
      .order('version_number', { ascending: false })
      .limit(1);
    if (!data || data.length === 0) {
      toast({ title: 'Tidak ada history', description: 'Belum ada versi sebelumnya' });
      return;
    }
    const prev = data[0];
    if (!confirm(`Undo ke versi #${prev.version_number} (${new Date(prev.created_at).toLocaleString('id-ID')})?`)) return;
    const { error } = await supabase.from('lua_scripts').update({
      content: prev.content, updated_at: new Date().toISOString(),
    }).eq('id', script.id);
    if (error) {
      toast({ title: 'Error', description: 'Gagal undo', variant: 'destructive' });
      return;
    }
    toast({ title: 'Undo berhasil', description: `Kembali ke v${prev.version_number}` });
    fetchScripts();
  };

  const getScriptUrl = (n: string) => `${SUPABASE_API_BASE}/get-loader?name=${encodeURIComponent(n)}`;
  const copyUrl = (n: string) => { navigator.clipboard.writeText(getScriptUrl(n)); toast({ title: 'Copied!' }); };
  const copyLoadstring = (n: string) => {
    navigator.clipboard.writeText(`loadstring(game:HttpGet("${getScriptUrl(n)}"))()`);
    toast({ title: 'Copied!', description: 'Loadstring disalin' });
  };

  return (
    <div className="space-y-4 sm:space-y-6">
      <div className="flex items-start justify-between gap-2">
        <div className="min-w-0 flex-1">
          <h2 className="text-lg sm:text-xl font-display font-semibold flex items-center gap-2">
            <Upload className="w-4 h-4 sm:w-5 sm:h-5 text-primary flex-shrink-0" />
            <span className="truncate">Upload Lua Scripts</span>
          </h2>
          <p className="text-xs sm:text-sm text-muted-foreground">
            Upload .lua — otomatis terintegrasi key system + whitelist database
          </p>
        </div>
        <div className="flex gap-1 flex-shrink-0">
          <Button variant="outline" size="sm" onClick={reWrapAll} disabled={rewrapping || scripts.length === 0} title="Re-wrap semua dengan wrapper terbaru">
            <RotateCcw className={`w-4 h-4 ${rewrapping ? 'animate-spin' : ''}`} />
          </Button>
          <Button variant="outline" size="sm" onClick={fetchScripts} disabled={loading}>
            <RefreshCw className={`w-4 h-4 ${loading ? 'animate-spin' : ''}`} />
          </Button>
        </div>
      </div>

      <Card className="glass-card">
        <CardContent className="p-4 sm:p-6">
          <input type="file" accept=".lua,.txt" ref={fileInputRef} onChange={handleUpload} className="hidden" />
          <div
            onClick={() => fileInputRef.current?.click()}
            className="border-2 border-dashed border-primary/30 rounded-xl p-6 sm:p-8 text-center cursor-pointer hover:border-primary/60 hover:bg-primary/5 transition-all"
          >
            <Upload className="w-8 h-8 sm:w-10 sm:h-10 mx-auto mb-3 text-primary/50" />
            <p className="text-sm font-medium mb-1">{uploading ? 'Uploading...' : 'Klik untuk upload file Lua'}</p>
            <p className="text-xs text-muted-foreground">File .lua atau .txt — auto-wrap key system + whitelist</p>
          </div>
          <div className="mt-3 p-2 rounded bg-primary/10 border border-primary/20">
            <div className="flex items-start gap-2 text-xs text-primary">
              <Shield className="w-3 h-3 flex-shrink-0 mt-0.5" />
              <span>Script otomatis cek <code className="text-[10px]">ArexansTools_Session.json</code> → kalau key valid langsung jalan, kalau tidak cek whitelist, kalau bukan whitelist minta input key.</span>
            </div>
          </div>
        </CardContent>
      </Card>

      <Card className="glass-card">
        <CardHeader className="pb-3 px-3 sm:px-6">
          <CardTitle className="text-sm sm:text-base flex items-center gap-2">
            <FileCode className="w-4 h-4 text-primary" />
            Script Ter-upload ({scripts.length})
          </CardTitle>
          <CardDescription className="text-xs">
            Semua script terproteksi key system + whitelist · Undo / History tersedia per script
          </CardDescription>
        </CardHeader>
        <CardContent className="px-3 sm:px-6">
          {scripts.length === 0 ? (
            <div className="text-center py-8 text-muted-foreground">
              <FileCode className="w-12 h-12 mx-auto mb-2 opacity-30" />
              <p className="text-sm">Belum ada script</p>
            </div>
          ) : (
            <ScrollArea className="max-h-[500px]">
              <div className="space-y-3">
                {scripts.map((script) => (
                  <div key={script.id} className="p-3 rounded-lg bg-muted/30 hover:bg-muted/50 transition-colors space-y-2">
                    <div className="flex items-center justify-between gap-2">
                      <div className="min-w-0 flex-1">
                        <div className="flex items-center gap-2 flex-wrap">
                          <p className="font-medium text-sm truncate">{script.display_name}</p>
                          <Badge variant="outline" className="text-[10px] px-1.5 py-0">
                            <Shield className="w-2.5 h-2.5 mr-0.5" />Key+WL
                          </Badge>
                        </div>
                        <p className="text-[10px] text-muted-foreground">{new Date(script.updated_at).toLocaleString('id-ID')}</p>
                      </div>
                      <div className="flex gap-1 flex-shrink-0">
                        <Button variant="ghost" size="sm" onClick={() => undoToPrevious(script)} title="Undo ke versi sebelumnya" className="h-8 px-2">
                          <Undo2 className="w-4 h-4" />
                        </Button>
                        <Button variant="ghost" size="sm" onClick={() => openHistory(script)} title="Lihat history" className="h-8 px-2">
                          <HistoryIcon className="w-4 h-4" />
                        </Button>
                        <Button variant="ghost" size="sm" onClick={() => deleteScript(script.id, script.display_name)} className="text-destructive hover:text-destructive h-8 px-2">
                          <Trash2 className="w-4 h-4" />
                        </Button>
                      </div>
                    </div>

                    <div className="space-y-1.5">
                      <div className="flex gap-1.5">
                        <Input readOnly value={getScriptUrl(script.name)} className="font-mono text-[10px] h-7 bg-black/30" />
                        <Button variant="outline" size="sm" className="h-7 px-2" onClick={() => copyUrl(script.name)}>
                          <Copy className="w-3 h-3" />
                        </Button>
                        <Button variant="outline" size="sm" className="h-7 px-2" onClick={() => window.open(getScriptUrl(script.name), '_blank')}>
                          <ExternalLink className="w-3 h-3" />
                        </Button>
                      </div>
                      <Button variant="outline" size="sm" className="w-full text-xs h-7" onClick={() => copyLoadstring(script.name)}>
                        <Copy className="w-3 h-3 mr-1" />
                        Copy Loadstring
                      </Button>
                    </div>
                  </div>
                ))}
              </div>
            </ScrollArea>
          )}
        </CardContent>
      </Card>

      <Card className="glass-card">
        <CardHeader className="pb-3 px-3 sm:px-6">
          <CardTitle className="text-sm sm:text-base flex items-center gap-2">
            <Shield className="w-4 h-4 text-yellow-500" />
            Fake Script API
          </CardTitle>
          <CardDescription className="text-xs">Endpoint fake source untuk user gagal autentikasi</CardDescription>
        </CardHeader>
        <CardContent className="px-3 sm:px-6 space-y-2">
          <div className="flex gap-1.5">
            <Input readOnly value={`${SUPABASE_API_BASE}/get-fake-script`} className="font-mono text-xs bg-black/30" />
            <Button variant="outline" size="sm" onClick={() => { navigator.clipboard.writeText(`${SUPABASE_API_BASE}/get-fake-script`); toast({ title: 'Copied!' }); }}>
              <Copy className="w-3 h-3" />
            </Button>
          </div>
        </CardContent>
      </Card>

      {/* History dialog */}
      <Dialog open={!!historyScript} onOpenChange={(o) => { if (!o) { setHistoryScript(null); setPreviewVersion(null); } }}>
        <DialogContent className="max-w-3xl max-h-[85vh] overflow-hidden flex flex-col">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <HistoryIcon className="w-4 h-4" />
              History: {historyScript?.display_name}
            </DialogTitle>
            <DialogDescription className="text-xs">
              Versi tersimpan otomatis tiap kali script diupdate (max 20 versi terakhir).
            </DialogDescription>
          </DialogHeader>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-3 overflow-hidden flex-1">
            <ScrollArea className="border rounded p-2 max-h-[60vh]">
              {versions.length === 0 ? (
                <p className="text-xs text-muted-foreground text-center py-8">Belum ada versi tersimpan</p>
              ) : (
                <div className="space-y-1">
                  {versions.map((v) => (
                    <button
                      key={v.id}
                      onClick={() => setPreviewVersion(v)}
                      className={`w-full text-left p-2 rounded text-xs hover:bg-muted/50 transition ${previewVersion?.id === v.id ? 'bg-primary/10 border border-primary/30' : ''}`}
                    >
                      <div className="font-medium">Versi #{v.version_number}</div>
                      <div className="text-[10px] text-muted-foreground">{new Date(v.created_at).toLocaleString('id-ID')}</div>
                    </button>
                  ))}
                </div>
              )}
            </ScrollArea>
            <div className="flex flex-col gap-2 overflow-hidden">
              {previewVersion ? (
                <>
                  <ScrollArea className="border rounded p-2 max-h-[50vh] bg-black/30">
                    <pre className="text-[10px] font-mono whitespace-pre-wrap break-all">{previewVersion.content.substring(0, 5000)}{previewVersion.content.length > 5000 ? '\n...(truncated)' : ''}</pre>
                  </ScrollArea>
                  <Button onClick={() => restoreVersion(previewVersion)} className="w-full">
                    <RotateCcw className="w-3 h-3 mr-1" />
                    Restore versi #{previewVersion.version_number}
                  </Button>
                </>
              ) : (
                <p className="text-xs text-muted-foreground text-center py-8">Pilih versi untuk preview</p>
              )}
            </div>
          </div>
        </DialogContent>
      </Dialog>
    </div>
  );
};

export default LuaUploadManager;
