import { FC, useState, useEffect, useRef } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Switch } from '@/components/ui/switch';
import { Checkbox } from '@/components/ui/checkbox';
import { toast } from '@/hooks/use-toast';
import { 
  FileCode, Save, RefreshCw, Copy, ExternalLink, Code2, 
  Eye, EyeOff, CheckCircle, AlertCircle, Upload, Globe, Shield, Wand2
} from 'lucide-react';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";

interface LuaScript {
  id: string;
  name: string;
  display_name: string;
  description: string | null;
  content: string;
  script_type: string;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

const WHITELIST_WRAPPER_TEMPLATE = `-- ========================================
-- WHITELIST PROTECTED SCRIPT
-- Auto-generated by Arexans System
-- ========================================

local HttpService = game:GetService("HttpService")
local Players = game:GetService("Players")

local WHITELIST_API = "{{API_URL}}/get-whitelist?format=json"
local CHECK_INTERVAL = 60

local whitelistCache = {}
local lastFetch = 0
local CACHE_DURATION = 30

local function fetchWhitelist()
    local success, result = pcall(function()
        local response = game:HttpGet(WHITELIST_API)
        local data = HttpService:JSONDecode(response)
        if data.success then return data.usernames end
        return {}
    end)
    if success then
        whitelistCache = result or {}
        lastFetch = tick()
        return true
    end
    return false
end

local function isWhitelisted(username)
    if tick() - lastFetch > CACHE_DURATION then fetchWhitelist() end
    for _, name in ipairs(whitelistCache) do
        if string.lower(name) == string.lower(username) then return true end
    end
    return false
end

local function getCurrentUsername()
    local player = Players.LocalPlayer
    if player then return player.Name end
    return nil
end

local function checkWhitelist()
    local username = getCurrentUsername()
    if not username then
        warn("[Whitelist] Could not get player username")
        return false
    end
    fetchWhitelist()
    if not isWhitelisted(username) then
        print("Loading script...")
        wait(2)
        for i = 1, 5 do
            print("Initializing module " .. i .. "/5...")
            wait(0.5)
        end
        print("Error: Connection timeout. Please try again later.")
        return false
    end
    return true
end

if not checkWhitelist() then
    return
end

print("[Arexans] Whitelist verified! Loading main script...")

-- ========================================
-- YOUR SCRIPT STARTS HERE
-- ========================================

{{USER_SCRIPT}}

-- Periodic check
spawn(function()
    while wait(CHECK_INTERVAL) do
        if not isWhitelisted(getCurrentUsername()) then
            warn("[Whitelist] User no longer whitelisted!")
        end
    end
end)
`;

const ScriptManagement: FC = () => {
  const [scripts, setScripts] = useState<LuaScript[]>([]);
  const [loading, setLoading] = useState(false);
  const [saving, setSaving] = useState<string | null>(null);
  const [editedContent, setEditedContent] = useState<Record<string, string>>({});
  const [showPreview, setShowPreview] = useState<Record<string, boolean>>({});
  const [enableWhitelistWrap, setEnableWhitelistWrap] = useState<Record<string, boolean>>({});
  const fileInputRefs = useRef<Record<string, HTMLInputElement | null>>({});
  const [selectedEndpoint, setSelectedEndpoint] = useState<'supabase' | 'current'>('supabase');

  const SUPABASE_API_BASE = `${import.meta.env.VITE_SUPABASE_URL}/functions/v1`;
  
  const getCurrentDomain = () => {
    if (typeof window !== 'undefined') {
      return `${window.location.protocol}//${window.location.host}`;
    }
    return '';
  };

  const currentDomain = getCurrentDomain();
  
  const getApiBase = () => {
    if (selectedEndpoint === 'current' && currentDomain) {
      return `${currentDomain}/api`;
    }
    return SUPABASE_API_BASE;
  };

  const fetchScripts = async () => {
    setLoading(true);
    try {
      const { data, error } = await supabase
        .from('lua_scripts')
        .select('*')
        .order('script_type');

      if (error) throw error;
      if (data) {
        setScripts(data);
        const content: Record<string, string> = {};
        data.forEach(s => { content[s.id] = s.content; });
        setEditedContent(content);
      }
    } catch (error) {
      console.error('Failed to fetch scripts:', error);
      toast({ title: 'Error', description: 'Gagal mengambil data scripts', variant: 'destructive' });
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchScripts();
  }, []);

  const wrapWithWhitelist = (userScript: string): string => {
    return WHITELIST_WRAPPER_TEMPLATE
      .replace('{{API_URL}}', SUPABASE_API_BASE)
      .replace('{{USER_SCRIPT}}', userScript);
  };

  const handleSaveScript = async (script: LuaScript) => {
    setSaving(script.id);
    try {
      let contentToSave = editedContent[script.id];
      
      if (enableWhitelistWrap[script.id] && script.script_type === 'main') {
        contentToSave = wrapWithWhitelist(editedContent[script.id]);
      }

      const { error } = await supabase
        .from('lua_scripts')
        .update({ 
          content: contentToSave,
          updated_at: new Date().toISOString()
        })
        .eq('id', script.id);

      if (error) throw error;
      
      const message = enableWhitelistWrap[script.id] && script.script_type === 'main'
        ? `Script "${script.display_name}" berhasil disimpan dengan whitelist protection`
        : `Script "${script.display_name}" berhasil disimpan`;
      
      toast({ title: 'Berhasil', description: message });
      fetchScripts();
      setEnableWhitelistWrap(prev => ({ ...prev, [script.id]: false }));
    } catch (error) {
      console.error('Failed to save script:', error);
      toast({ title: 'Error', description: 'Gagal menyimpan script', variant: 'destructive' });
    } finally {
      setSaving(null);
    }
  };

  const handleToggleActive = async (script: LuaScript) => {
    try {
      const { error } = await supabase
        .from('lua_scripts')
        .update({ 
          is_active: !script.is_active,
          updated_at: new Date().toISOString()
        })
        .eq('id', script.id);

      if (error) throw error;
      
      toast({ 
        title: 'Berhasil', 
        description: `Script "${script.display_name}" ${!script.is_active ? 'diaktifkan' : 'dinonaktifkan'}` 
      });
      fetchScripts();
    } catch (error) {
      console.error('Failed to toggle script:', error);
      toast({ title: 'Error', description: 'Gagal mengubah status script', variant: 'destructive' });
    }
  };

  const getScriptUrl = (scriptName: string) => {
    return `${getApiBase()}/get-script?name=${scriptName}`;
  };

  const copyScriptUrl = (scriptName: string) => {
    navigator.clipboard.writeText(getScriptUrl(scriptName));
    toast({ title: 'Copied!', description: 'URL script berhasil disalin' });
  };

  const getLoaderUrlForBrowser = (scriptName: string) => {
    // Pretty URL for the main keysystem loader on the published domain (browser will see Access Denied).
    if (scriptName === 'keysystem' && import.meta.env.PROD && currentDomain) {
      return `${currentDomain}/loader`;
    }
    return `${getApiBase()}/get-loader?name=${encodeURIComponent(scriptName)}`;
  };

  const getLoaderUrlForExecutor = (scriptName: string) => {
    // Force-raw mode bypasses browser redirect heuristics so executors get pure Lua.
    // Always prefer Cloud API base to avoid needing /api proxy on the current domain.
    return `${SUPABASE_API_BASE}/get-loader?name=${encodeURIComponent(scriptName)}`;
  };

  const copyLoadstringCode = (scriptName: string) => {
    const url = getLoaderUrlForExecutor(scriptName);
    const code = `loadstring(game:HttpGet("${url}"))()`;

    navigator.clipboard.writeText(code);
    toast({ title: 'Copied!', description: 'Loadstring code berhasil disalin' });
  };

  const getScriptTypeColor = (type: string) => {
    switch (type) {
      case 'loader': return 'bg-primary/20 text-primary';
      case 'main': return 'bg-secondary/20 text-secondary';
      case 'whitelist': return 'bg-yellow-500/20 text-yellow-500';
      default: return 'bg-muted text-muted-foreground';
    }
  };

  const getScriptTypeLabel = (type: string) => {
    switch (type) {
      case 'loader': return 'Key System';
      case 'main': return 'Main Script';
      case 'whitelist': return 'Whitelist Checker';
      default: return type;
    }
  };

  const hasChanges = (script: LuaScript) => {
    return editedContent[script.id] !== script.content;
  };

  const handleFileUpload = (scriptId: string, event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (!file) return;

    const validExtensions = ['.lua', '.txt'];
    const fileExtension = file.name.toLowerCase().substring(file.name.lastIndexOf('.'));
    
    if (!validExtensions.includes(fileExtension)) {
      toast({ title: 'Error', description: 'Hanya file .lua atau .txt yang diperbolehkan', variant: 'destructive' });
      return;
    }

    const reader = new FileReader();
    reader.onload = (e) => {
      const content = e.target?.result as string;
      setEditedContent(prev => ({ ...prev, [scriptId]: content }));
      toast({ title: 'File Loaded', description: `File "${file.name}" berhasil dimuat` });
    };
    reader.onerror = () => {
      toast({ title: 'Error', description: 'Gagal membaca file', variant: 'destructive' });
    };
    reader.readAsText(file);
    event.target.value = '';
  };

  return (
    <div className="space-y-4 sm:space-y-6">
      {/* Header */}
      <div className="flex flex-col gap-3">
        <div className="flex items-start justify-between gap-2">
          <div className="min-w-0 flex-1">
            <h2 className="text-lg sm:text-xl font-display font-semibold flex items-center gap-2">
              <FileCode className="w-4 h-4 sm:w-5 sm:h-5 text-primary flex-shrink-0" />
              <span className="truncate">Lua Script Manager</span>
            </h2>
            <p className="text-xs sm:text-sm text-muted-foreground">
              Edit dan kelola script Lua untuk Roblox
            </p>
          </div>
          <Button variant="outline" size="sm" onClick={fetchScripts} disabled={loading} className="flex-shrink-0">
            <RefreshCw className={`w-4 h-4 ${loading ? 'animate-spin' : ''}`} />
            <span className="hidden sm:inline ml-2">Refresh</span>
          </Button>
        </div>
      </div>

      {/* Domain Selector Card */}
      <Card className="glass-card">
        <CardHeader className="pb-3 px-3 sm:px-6">
          <CardTitle className="text-sm sm:text-base flex items-center gap-2">
            <Globe className="w-4 h-4 text-primary" />
            API Endpoint
          </CardTitle>
          <CardDescription className="text-xs">
            Pilih endpoint URL untuk script
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-3 px-3 sm:px-6">
          <div className="space-y-3">
            <div>
              <Label className="text-xs mb-1.5 block">Endpoint Type</Label>
              <Select 
                value={selectedEndpoint} 
                onValueChange={(v: 'supabase' | 'current') => setSelectedEndpoint(v)}
              >
                <SelectTrigger className="w-full text-xs sm:text-sm">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="supabase">Cloud API (Default)</SelectItem>
                  <SelectItem value="current">Current Domain ({currentDomain})</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="p-2 rounded bg-muted/50 overflow-x-auto">
              <code className="text-xs font-mono text-muted-foreground break-all">
                {getApiBase()}
              </code>
            </div>
          </div>
          
          {selectedEndpoint === 'current' && (
            <div className="p-2 rounded bg-yellow-500/10 border border-yellow-500/30">
              <p className="text-xs text-yellow-600 dark:text-yellow-400">
                ⚠️ Untuk menggunakan domain saat ini, Anda perlu setup proxy/redirect di hosting Anda 
                yang mengarahkan <code className="font-mono">/api/*</code> ke <code className="font-mono">{SUPABASE_API_BASE}/*</code>
              </p>
            </div>
          )}
        </CardContent>
      </Card>

      {/* Script Cards */}
      <div className="grid gap-4 sm:gap-6">
        {scripts.map((script) => (
          <Card key={script.id} className="glass-card overflow-hidden">
            <CardHeader className="pb-3 px-3 sm:px-6">
              <div className="flex flex-col gap-3">
                <div className="flex items-start gap-2 sm:gap-3">
                  <Code2 className="w-4 h-4 sm:w-5 sm:h-5 text-primary flex-shrink-0 mt-0.5" />
                  <div className="min-w-0 flex-1">
                    <div className="flex flex-wrap items-center gap-2">
                      <CardTitle className="text-base sm:text-lg">{script.display_name}</CardTitle>
                      <span className={`px-2 py-0.5 rounded text-xs font-medium flex-shrink-0 ${getScriptTypeColor(script.script_type)}`}>
                        {getScriptTypeLabel(script.script_type)}
                      </span>
                    </div>
                    <CardDescription className="text-xs sm:text-sm mt-0.5">
                      {script.description || `Script ${script.script_type}`}
                    </CardDescription>
                  </div>
                </div>
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <Switch
                      checked={script.is_active}
                      onCheckedChange={() => handleToggleActive(script)}
                    />
                    <span className={`text-xs sm:text-sm ${script.is_active ? 'text-secondary' : 'text-muted-foreground'}`}>
                      {script.is_active ? 'Active' : 'Inactive'}
                    </span>
                  </div>
                  {hasChanges(script) && (
                    <span className="flex items-center gap-1 text-xs text-yellow-500">
                      <AlertCircle className="w-3 h-3" />
                      Unsaved
                    </span>
                  )}
                </div>
              </div>
            </CardHeader>
            <CardContent className="space-y-4 px-3 sm:px-6">
              {/* Script Editor */}
              <div className="space-y-2">
                <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2">
                  <Label className="text-xs sm:text-sm font-medium">Script Content</Label>
                  <div className="flex items-center gap-2">
                    <input
                      type="file"
                      accept=".lua,.txt"
                      ref={el => fileInputRefs.current[script.id] = el}
                      onChange={(e) => handleFileUpload(script.id, e)}
                      className="hidden"
                    />
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={() => fileInputRefs.current[script.id]?.click()}
                      className="text-xs"
                    >
                      <Upload className="w-3 h-3 sm:w-4 sm:h-4" />
                      <span className="ml-1 hidden xs:inline">Upload</span>
                    </Button>
                    <Button
                      variant="ghost"
                      size="sm"
                      onClick={() => setShowPreview(prev => ({ ...prev, [script.id]: !prev[script.id] }))}
                      className="text-xs"
                    >
                      {showPreview[script.id] ? (
                        <><EyeOff className="w-3 h-3 sm:w-4 sm:h-4" /><span className="ml-1 hidden xs:inline">Hide</span></>
                      ) : (
                        <><Eye className="w-3 h-3 sm:w-4 sm:h-4" /><span className="ml-1 hidden xs:inline">Preview</span></>
                      )}
                    </Button>
                  </div>
                </div>
                <Textarea
                  value={editedContent[script.id] || ''}
                  onChange={(e) => setEditedContent(prev => ({ ...prev, [script.id]: e.target.value }))}
                  className="font-mono text-xs sm:text-sm min-h-[200px] sm:min-h-[300px] bg-black/50 border-primary/30"
                  placeholder="-- Enter your Lua script here..."
                  spellCheck={false}
                />
                {showPreview[script.id] && (
                  <div className="p-2 sm:p-3 rounded bg-black/30 border border-muted overflow-hidden">
                    <pre className="text-xs text-muted-foreground whitespace-pre-wrap font-mono break-all">
                      {editedContent[script.id]?.slice(0, 500)}
                      {(editedContent[script.id]?.length || 0) > 500 && '...'}
                    </pre>
                  </div>
                )}
                
                {/* Whitelist Protection Option for Main Script */}
                {script.script_type === 'main' && (
                  <div className="p-3 rounded bg-primary/10 border border-primary/30">
                    <div className="flex items-start gap-3">
                      <Checkbox
                        id={`whitelist-${script.id}`}
                        checked={enableWhitelistWrap[script.id] || false}
                        onCheckedChange={(checked) => 
                          setEnableWhitelistWrap(prev => ({ ...prev, [script.id]: !!checked }))
                        }
                      />
                      <div className="flex-1">
                        <label 
                          htmlFor={`whitelist-${script.id}`}
                          className="text-sm font-medium cursor-pointer flex items-center gap-2"
                        >
                          <Shield className="w-4 h-4 text-primary" />
                          Aktifkan Whitelist Protection
                        </label>
                        <p className="text-xs text-muted-foreground mt-1">
                          Script akan otomatis di-wrap dengan kode whitelist checker. 
                          Player yang tidak ada di whitelist akan di-kick dan menjalankan script palsu.
                        </p>
                        {enableWhitelistWrap[script.id] && (
                          <div className="mt-2 p-2 rounded bg-secondary/20 flex items-center gap-2">
                            <Wand2 className="w-4 h-4 text-secondary" />
                            <span className="text-xs text-secondary">Script akan di-wrap saat disimpan</span>
                          </div>
                        )}
                      </div>
                    </div>
                  </div>
                )}
              </div>

              {/* API URLs */}
              <div className="p-2 sm:p-3 rounded bg-muted/30 space-y-3">
                <Label className="text-xs sm:text-sm font-medium">API Endpoints</Label>
                <div className="space-y-2">
                  <div className="flex flex-col gap-2">
                    <Input
                      readOnly
                      value={getScriptUrl(script.name)}
                      className="font-mono text-xs bg-black/30 w-full"
                    />
                    <div className="flex gap-2">
                      <Button variant="outline" size="sm" onClick={() => copyScriptUrl(script.name)} className="flex-1 text-xs">
                        <Copy className="w-3 h-3 sm:w-4 sm:h-4 mr-1" />
                        Copy URL
                      </Button>
                      <Button variant="outline" size="sm" onClick={() => window.open(getScriptUrl(script.name), '_blank')} className="flex-shrink-0">
                        <ExternalLink className="w-3 h-3 sm:w-4 sm:h-4" />
                      </Button>
                    </div>
                  </div>
                </div>

                <div className="space-y-1.5">
                  <Label className="text-xs text-muted-foreground">Loadstring Code:</Label>
                  <div className="flex flex-col gap-2">
                    <div className="p-2 rounded bg-black/50 overflow-x-auto">
                      <code className="text-xs font-mono text-secondary whitespace-nowrap block">
                        {`loadstring(game:HttpGet("${getLoaderUrlForExecutor(script.name)}"))()`}
                      </code>
                    </div>
                    <Button variant="outline" size="sm" onClick={() => copyLoadstringCode(script.name)} className="w-full text-xs">
                      <Copy className="w-3 h-3 sm:w-4 sm:h-4 mr-1" />
                      Copy Loadstring
                    </Button>
                  </div>
                </div>
              </div>

              {/* Actions */}
              <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-2 pt-2">
                <span className="text-xs text-muted-foreground">
                  Updated: {new Date(script.updated_at).toLocaleString('id-ID')}
                </span>
                <Button
                  onClick={() => handleSaveScript(script)}
                  disabled={!hasChanges(script) || saving === script.id}
                  className="w-full sm:w-auto gap-2 text-xs sm:text-sm"
                  size="sm"
                >
                  {saving === script.id ? (
                    <><RefreshCw className="w-3 h-3 sm:w-4 sm:h-4 animate-spin" /> Saving...</>
                  ) : (
                    <><Save className="w-3 h-3 sm:w-4 sm:h-4" /> Save Script</>
                  )}
                </Button>
              </div>
            </CardContent>
          </Card>
        ))}
      </div>

      {/* Usage Guide */}
      <Card className="glass-card">
        <CardHeader className="px-3 sm:px-6">
          <CardTitle className="text-base sm:text-lg flex items-center gap-2">
            <CheckCircle className="w-4 h-4 sm:w-5 sm:h-5 text-secondary" />
            Cara Penggunaan
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-4 text-sm px-3 sm:px-6">
          <div className="grid gap-3 sm:gap-4 grid-cols-1 md:grid-cols-3">
            <div className="p-2 sm:p-3 rounded bg-muted/30">
              <h4 className="font-semibold text-primary mb-1 sm:mb-2 text-xs sm:text-sm">1. Key System Loader</h4>
              <p className="text-muted-foreground text-xs">
                Script ini adalah entry point. Berisi UI untuk input key dan validasi ke API. 
                Setelah key valid, script ini akan memuat Main Script dari server.
              </p>
            </div>
            <div className="p-2 sm:p-3 rounded bg-muted/30">
              <h4 className="font-semibold text-secondary mb-1 sm:mb-2 text-xs sm:text-sm">2. Main Script</h4>
              <p className="text-muted-foreground text-xs">
                Script utama yang berisi fitur-fitur tool Anda. Script ini hanya bisa diakses 
                setelah validasi key berhasil, melindungi kode Anda dari pencurian.
              </p>
            </div>
            <div className="p-2 sm:p-3 rounded bg-muted/30">
              <h4 className="font-semibold text-yellow-500 mb-1 sm:mb-2 text-xs sm:text-sm">3. Whitelist Checker</h4>
              <p className="text-muted-foreground text-xs">
                Script untuk mengecek apakah username Roblox terdaftar di whitelist.
                Jika tidak terdaftar, player akan di-kick otomatis.
              </p>
            </div>
          </div>
          
          <div className="p-2 sm:p-3 rounded bg-yellow-500/10 border border-yellow-500/30">
            <h4 className="font-semibold mb-1 sm:mb-2 text-xs sm:text-sm text-yellow-500">🛡️ Whitelist API Endpoints:</h4>
            <div className="space-y-2 text-xs text-muted-foreground">
              <div className="flex flex-col gap-1">
                <span className="font-medium">JSON Format:</span>
                <code className="font-mono text-yellow-500 break-all">{getApiBase()}/get-whitelist?format=json</code>
              </div>
              <div className="flex flex-col gap-1">
                <span className="font-medium">Lua Table Format:</span>
                <code className="font-mono text-yellow-500 break-all">{getApiBase()}/get-whitelist?format=lua</code>
              </div>
              <div className="flex flex-col gap-1">
                <span className="font-medium">Raw List (per line):</span>
                <code className="font-mono text-yellow-500 break-all">{getApiBase()}/get-whitelist?format=raw</code>
              </div>
            </div>
          </div>
          
           <div className="p-2 sm:p-3 rounded bg-primary/10 border border-primary/30">
             <h4 className="font-semibold mb-1 sm:mb-2 text-xs sm:text-sm">💡 Contoh Penggunaan di Roblox:</h4>
             <div className="overflow-x-auto">
               <code className="text-xs font-mono text-primary whitespace-nowrap block">
                 {`loadstring(game:HttpGet(\"${import.meta.env.PROD ? `${currentDomain}/loader` : `${SUPABASE_API_BASE}/get-loader?name=keysystem`}\"))()`}
               </code>
             </div>
           </div>
        </CardContent>
      </Card>
    </div>
  );
};

export default ScriptManagement;
