
UPDATE lua_scripts 
SET content = replace(
  content,
  E'    -- ExpirationLabel is now a child of MainFrame, positioned below the TitleBar\n    local ExpirationLabel = Instance.new("TextLabel")\n    ExpirationLabel.Name = "ExpirationLabel"\n    ExpirationLabel.Size = UDim2.new(1, -10, 0, 16)\n    ExpirationLabel.Position = UDim2.new(0, 5, 1, -17) -- Bottom with padding\n    ExpirationLabel.BackgroundTransparency = 1\n    ExpirationLabel.Text = "Loading expiry..."\n    ExpirationLabel.TextColor3 = RoleLabel.TextColor3\n    ExpirationLabel.TextScaled = false\n    ExpirationLabel.TextSize = 11\n    ExpirationLabel.TextTruncate = Enum.TextTruncate.None\n    ExpirationLabel.RichText = true\n    ExpirationLabel.Font = Enum.Font.SourceSans\n    ExpirationLabel.Parent = MainFrame',
  E'    -- ExpirationLabel is now a child of MainFrame, positioned below the TitleBar\n    ExpirationLabel = Instance.new("TextLabel")\n    ExpirationLabel.Name = "ExpirationLabel"\n    ExpirationLabel.Size = UDim2.new(1, -10, 0, 16)\n    ExpirationLabel.Position = UDim2.new(0, 5, 1, -17) -- Bottom with padding\n    ExpirationLabel.BackgroundTransparency = 1\n    ExpirationLabel.TextColor3 = RoleLabel.TextColor3\n    ExpirationLabel.TextScaled = false\n    ExpirationLabel.TextSize = 11\n    ExpirationLabel.TextTruncate = Enum.TextTruncate.None\n    ExpirationLabel.RichText = true\n    ExpirationLabel.Font = Enum.Font.SourceSans\n    ExpirationLabel.Parent = MainFrame\n\n    -- Start countdown immediately via task.spawn so it works even if later code errors\n    task.spawn(function()\n        while ExpirationLabel and ExpirationLabel.Parent do\n            local remainSec = expirationTimestamp - os.time()\n            if remainSec < 1 then\n                ExpirationLabel.Text = "EXPIRED"\n                break\n            end\n            local d = math.floor(remainSec / 86400)\n            local r = remainSec % 86400\n            local h = math.floor(r / 3600)\n            r = r % 3600\n            local m = math.floor(r / 60)\n            local s = r % 60\n            ExpirationLabel.Text = string.format("Expires in: %dD %02dH %02dM %02dS", d, h, m, s)\n            task.wait(1)\n        end\n    end)'
),
updated_at = now()
WHERE name = 'main';
